use std::fs;
use std::path::Path;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

#[test]
fn compares_the_working_lockfile_with_a_git_revision() {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let repository =
        std::env::temp_dir().join(format!("cargo-depdep-cli-{}-{nonce}", std::process::id()));
    fs::create_dir(&repository).unwrap();

    git(&repository, &["init", "--initial-branch=main"]);
    fs::write(
        repository.join("Cargo.lock"),
        lockfile(&[
            ("foo", "1.0.0"),
            ("foo", "2.0.0"),
            ("removed", "4.0.0"),
            ("unchanged", "1.2.3"),
        ]),
    )
    .unwrap();
    git(&repository, &["add", "Cargo.lock"]);
    git(
        &repository,
        &[
            "-c",
            "user.name=Test",
            "-c",
            "user.email=test@example.com",
            "-c",
            "commit.gpgsign=false",
            "commit",
            "-m",
            "old lockfile",
        ],
    );

    fs::write(
        repository.join("Cargo.lock"),
        lockfile(&[
            ("added", "0.1.0"),
            ("foo", "2.0.0"),
            ("foo", "3.0.0"),
            ("unchanged", "1.2.3"),
        ]),
    )
    .unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_cargo-depdep"))
        .args(["depdep", "--rev", "HEAD"])
        .current_dir(&repository)
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "command failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8(output.stdout).unwrap(),
        "| crate | old | new |\n\
         | --- | --- | --- |\n\
         | added |  | 0.1.0 |\n\
         | foo | 1.0.0, 2.0.0 | 2.0.0, 3.0.0 |\n\
         | removed | 4.0.0 |  |\n"
    );

    let pretty = Command::new(env!("CARGO_BIN_EXE_cargo-depdep"))
        .args(["depdep", "--pretty", "--rev", "HEAD"])
        .current_dir(&repository)
        .output()
        .unwrap();

    assert!(
        pretty.status.success(),
        "command failed: {}",
        String::from_utf8_lossy(&pretty.stderr)
    );
    assert_eq!(
        String::from_utf8(pretty.stdout).unwrap(),
        "| crate   |          old |          new |\n\
         | :------ | -----------: | -----------: |\n\
         | added   |              |        0.1.0 |\n\
         | foo     | 1.0.0, 2.0.0 | 2.0.0, 3.0.0 |\n\
         | removed |        4.0.0 |              |\n"
    );

    fs::remove_dir_all(repository).unwrap();
}

fn git(repository: &Path, arguments: &[&str]) {
    let output = Command::new("git")
        .args(arguments)
        .current_dir(repository)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {arguments:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn lockfile(packages: &[(&str, &str)]) -> String {
    let mut contents =
        String::from("# This file is automatically @generated by Cargo.\nversion = 4\n");
    for (name, version) in packages {
        contents.push_str(&format!(
            "\n[[package]]\nname = \"{name}\"\nversion = \"{version}\"\n"
        ));
    }
    contents
}
